# Generated by Django 3.2.9 on 2022-01-14 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_centralpicture_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='central_picture',
            new_name='pictures',
        ),
    ]
